extend type Query {
    getHomePage(request: GetHomePageRequest!): GetHomePageResponse!
    getGamePage(request: GetGamePageRequest!): GetGamePageResponse!
    getContinuePlayingPage(request: GetContinuePlayingPageRequest!): GetContinuePlayingPageResponse!
    getFilterPage(request: GetFilterPageRequest!): GetFilterPageResponse!
    getSearchPage(request: GetSearchPageRequest!): GetSearchPageResponse!
    getSiteMapPage(request: GetSiteMapPageRequest!): GetSiteMapPageResponse!
    getWizardPage(request: GetWizardPageRequest!): GetWizardPageResponse!
    getTagPage(request: GetTagPageRequest!): GetTagPageResponse!
    getTagsPage(request: GetTagsPageRequest!): GetTagsPageResponse!
    getCategoryPage(request: GetCategoryPageRequest!): GetCategoryPageResponse!
    getCategoriesPage(request: GetCategoriesPageRequest!): GetCategoriesPageResponse!
}

input GetCategoriesPageRequest {
    language: Language!
}

type GetCategoriesPageResponse {
    data: ListCategoriesResponse!
}

input GetTagsPageRequest {
    language: Language!
    page: Int!
}

type GetTagsPageResponse {
    data: ListTagsResponse!
}

input GetTagPageRequest {
    language: Language!
    tagID: Int!
    page: Int!
}

type GetTagPageResponse {
    tag: GetTagResponse!
    games: ListGamesResponse!
}

input GetWizardPageRequest {
    language: Language!
    categoryIDs: [Int!]!
}

type GetWizardPageResponse {
    categories: ListCategoriesResponse!
    games: ListGamesResponse!
}

input GetSiteMapPageRequest {
    language: Language!
}

type GetSiteMapPageResponse {
    categories: ListCategoriesResponse!
}

input GetSearchPageRequest {
    language: Language!
    query: String!
    page: Int!
    sort: SortingMethod
}

type GetSearchPageResponse {
    items: [SearchItem!]
    total: Int!
    showingRange: String!
}

input GetContinuePlayingPageRequest{
    lastPlayedGameIDs: [Int!]!
    page: Int!
    language: Language!
}

type GetContinuePlayingPageResponse {
    data: ListGamesResponse!
}

input GetFilterPageRequest {
    categoryIDs: [Int!]
    sort: SortingMethod
    tagIDs: [Int!]
    gameIDs: [Int!]
    page: Int!
    language: Language!
}

type GetFilterPageResponse {
    data: ListGamesResponse!
}

type GetCategoryPageResponse {
    category: GetCategoryResponse!
    firstSectionGames: ListGamesResponse!
    tagSections: [TagSection!]!
    tags: ListTagsResponse!
    otherGames: ListGamesResponse!
}

type GetHomePageResponse {
    totalGames: Int!
    totalGamesAddedInLast7Days: Int!
    mostPlayedGamesInLast7Days: ListGamesResponse!
    gamesAddedInLast7Days: ListGamesResponse!
    mostPlayedGames: ListGamesResponse!
    sections: GetWebsiteSectionsPlacementResponse!
    tagSection: [TagSection!]!
}

type GetGamePageResponse {
    game: GetGameResponse!
    otherGames: ListGamesResponse!
    isLiked: Boolean!
    isDisliked: Boolean!
    fullScreenPageURL: String!
}

type TagSection {
    games: ListGamesResponse
    tag: Tag!
}

input GetHomePageRequest {
    language: Language!
    lastPlayedGameIDs: [Int!]
}

input GetCategoryPageRequest {
    language: Language!
    slug: String!
    id: Int!
}

input GetGamePageRequest {
    language: Language!
    slug: String!
    lastPlayedGameIDs: [Int]
    likedGameIDs: [Int]
    dislikedGameIDs: [Int]
}
