environment: "development"
logLevel: "debug"
port: 3000

postgresql:
  connectionString: "host=localhost user=vedia password=123 dbname=vediagames port=5432 sslmode=disable"
  path:
    migration: "db/schema"
    stub: "db/data"

sendinblue:
  key: "empty"

bucket:
  key: "empty"
  secret: "empty"
  region: "us-west-004"
  endpoint: "https://s3.us-west-004.backblazeb2.com"
  bucket: "vg-images"

cors:
  allowedOrigins:
    - "*"

redisAddress: "localhost:6379"


imagor:
  URL: "localhost:8000"
  secret: "vediagames"

bunnyStorage:
  URL: "[zone]storage.bunnycdn.com"
  zone: "vediagames"
  accessKey: "UUID"