environment: "development"
logLevel: "debug"
port: 3000

postgresql:
  vediaGamesConnectionString: "host=localhost user=vedia password=123 dbname=vediagames port=5432 sslmode=disable"
  mommaGamesConnectionString: "host=localhost user=vedia password=123 dbname=vediagames port=5432 sslmode=disable"
  path:
    migration: "db/schema"
    stub: "db/data"

sendinblue:
  key: "empty"

cors:
  allowedOrigins:
    - "*"

redisAddress: "localhost:6379"

bigquery:
  projectID: "your-project-id"
  credentialsPath: "path/to/your/credentials.json"
  tableID: "table"
  datasetID: "dataset"

imagor:
  URL: "localhost:8000"
  secret: "vediagames"

bunnyStorage:
  URL: "storage.bunnycdn.com"
  zone: "vediagames"
  accessKey: "UUID"
