version: "3.8"
services:
  postgres:
    image: "postgres:15.0-alpine"
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=vedia
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=vediagames
    volumes:
      - database-data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - "redis-data:/var/lib/redis/data"
  kratos-migrate:
    depends_on:
      - postgres
    container_name: kratos-migrate
    image: oryd/kratos:v0.10.1
    environment:
      - DSN=postgres://vedia:123@postgres:5432/auth?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate sql -e --yes
  kratos:
    container_name: kratos
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.10.1
    # watch-courier is set for sending verification/recovery emails
    command: serve -c /etc/kratos/config/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config
        target: /etc/kratos/config
      - type: bind
        source: ./identity-schemas
        target: /etc/kratos/identity-schemas
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
volumes:
  database-data:
  redis-data:
