version: "3.8"
services:
  postgres:
    image: "postgres:15.0-alpine"
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=vedia
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=vediagames
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./db/data/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/var/lib/redis/data"

  kratos:
    container_name: kratos
    image: oryd/kratos:v0.11.0
    command: serve -c /etc/kratos/local.config.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/kratos
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
volumes:
  database-data:
  redis-data:
