version: "3.8"
services:
  postgres:
    image: "postgres:15.0-alpine"
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
       # persist data even if container shuts down
    environment:
      - POSTGRES_USER=vedia
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=vediagames
    volumes:
      - database-data:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - "redis-data:/var/lib/redis/data"

volumes:
  database-data:
  redis-data:
