version: "3.8"
services:
  postgres:
    image: "postgres:15.0-alpine"
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=vedia
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=vediagames
    volumes:
      - $PG_MOUNT:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - $REDIS_MOUNT:/var/lib/redis/data

  imagor:
    image: shumc/imagor:1.4.2
    environment:
      PORT: 8000
      IMAGOR_SECRET: vediagames
      IMAGOR_SIGNER_TYPE: sha256
      IMAGOR_SIGNER_TRUNCATE: 40
    ports:
      - "8000:8000"

        #  kratos:
        #    container_name: kratos
        #    depends_on:
        #      - kratos-migrate
        #    image: oryd/kratos:v0.11.0
        #    command: serve -c /etc/kratos/local.config.yml --dev --watch-courier
        #    volumes:
        #      - type: bind
        #        source: ./kratos
        #        target: /etc/kratos
        #    ports:
        #      - "4433:4433" # public
        #      - "4434:4434" # admin
        #
        #  kratos-migrate:
        #    depends_on:
        #      - postgres
        #    container_name: kratos-migrate
        #    image: oryd/kratos:v0.11.0
        #    environment:
        #      - DSN=postgres://vedia:123@postgres:5432/auth?sslmode=disable&max_conns=20&max_idle_conns=4
        #    command: migrate sql -e --yes
        #
        #  mailslurper:
        #    image: oryd/mailslurper:latest-smtps
        #    ports:
        #      - "4436:4436"
        #      - "4437:4437"
        #
volumes:
  database-data:
  redis-data:
