version: "3.8"
services:
  postgres:
    image: "postgres:15.0-alpine"
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=vedia
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=vediagames
    volumes:
      - database-data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - "redis-data:/var/lib/redis/data"
  imagor:
    image: shumc/imagor:1.3.5
    environment:
      PORT: 8000
      IMAGOR_SECRET: vediagames
      IMAGOR_SIGNER_TYPE: sha256
      IMAGOR_SIGNER_TRUNCATE: 40
    ports:
      - "8000:8000"

volumes:
  database-data:
  redis-data:
