package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/vediagames/vediagames.com/bff/graphql/model"
	"github.com/vediagames/vediagames.com/gateway/graphql/generated"
	model1 "github.com/vediagames/vediagames.com/gateway/graphql/model"
)

// Tags is the resolver for the tags field.
func (r *gameResolver) Tags(ctx context.Context, obj *model.Game) (*model1.Tags, error) {
	panic(fmt.Errorf("not implemented: Tags - tags"))
}

// Categories is the resolver for the categories field.
func (r *gameResolver) Categories(ctx context.Context, obj *model.Game) (*model1.Categories, error) {
	panic(fmt.Errorf("not implemented: Categories - categories"))
}

// Tags is the resolver for the tags field.
func (r *sectionResolver) Tags(ctx context.Context, obj *model.Section) (*model1.Tags, error) {
	panic(fmt.Errorf("not implemented: Tags - tags"))
}

// Categories is the resolver for the categories field.
func (r *sectionResolver) Categories(ctx context.Context, obj *model.Section) (*model1.Categories, error) {
	panic(fmt.Errorf("not implemented: Categories - categories"))
}

// Games is the resolver for the games field.
func (r *sectionResolver) Games(ctx context.Context, obj *model.Section) (*model1.Games, error) {
	panic(fmt.Errorf("not implemented: Games - games"))
}

// Games is the resolver for the games field.
func (r *tagSectionResolver) Games(ctx context.Context, obj *model.TagSection) (*model1.Games, error) {
	panic(fmt.Errorf("not implemented: Games - games"))
}

// Game returns generated.GameResolver implementation.
func (r *Resolver) Game() generated.GameResolver { return &gameResolver{r} }

// Section returns generated.SectionResolver implementation.
func (r *Resolver) Section() generated.SectionResolver { return &sectionResolver{r} }

// TagSection returns generated.TagSectionResolver implementation.
func (r *Resolver) TagSection() generated.TagSectionResolver { return &tagSectionResolver{r} }

type gameResolver struct{ *Resolver }
type sectionResolver struct{ *Resolver }
type tagSectionResolver struct{ *Resolver }
