version: 2.1

commands:
  setup-env:
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c3:a9:2f:40:e6:1b:2c:35:bb:57:59:5b:7d:49:13:60"
            - "9f:ba:c1:5b:ef:7f:f1:73:44:bf:3c:d3:12:0b:bf:ce"
      - run: git config --global --add url."ssh://git@github.com/vediagames/".insteadOf "https://github.com/vediagames/"
      - run: go env -w GOPRIVATE="github.com/vediagames"

jobs:
  build:
    docker:
      - image: cimg/go:1.19.3
    working_directory: ~/vediagames.com
    environment:
      CGO_ENABLED: 0
    steps:
      - setup-env
      - run: go build -a -ldflags '-w -extldflags "-static"'  ./...

  lint:
    docker:
      - image: golangci/golangci-lint:v1.50.1
    steps:
      - setup-env
      - run: golangci-lint run -v

  test:
    docker:
      - image: cimg/go:1.19.3
    working_directory: ~/vediagames.com
    parallelism: 4
    steps:
      - setup-env
      - run: go test -v -race $(go list ./... | circleci tests split --split-by=timings)

workflows:
  build_lint_test:
    jobs:
      - build
      - lint
      - test
