version: v0.10.1

dsn: postgres://vedia:123@postgres:5432/auth?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
  admin:
    base_url: http://localhost:4434/

selfservice:
  # 
  default_browser_return_url: http://vediagames_url/
  allowed_return_urls:
    - http://vediagames_url

  methods:
    password:
      enabled: true

    link:
      enabled: true
      config:
        lifespan: 15m

  flows:
    error:
      ui_url: http://vediagames_url/error

    settings:
      ui_url: http://vediagames_url/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://vediagames_url/recovery

    verification:
      enabled: true
      ui_url: http://vediagames_url/verification
      after:
        hooks:
          - hook: web_hook
            config:
              url: http://self-service-go:4455/
              method: POST # GET, DELETE, etc
              body: file:///etc/kratos/config/identity.jsonnet

    logout:
      after:
        default_browser_return_url: http://vediagames_url/login

    login:
      lifespan: 10m
      ui_url: http://vediagames_url/login
      after:
        default_browser_return_url: "http://vediagames_url/dashboard"
        password:
          hooks:
            - hook: require_verified_address

    registration:
      lifespan: 10m
      ui_url: http://vediagames_url/registration
      after:
        default_browser_return_url: http://vediagames_url/registered
        hooks:
          - hook: web_hook
            config:
              url: http://self-service-go:4455/
              method: POST # GET, DELETE, etc
              body: file:///etc/kratos/config/identity.jsonnet

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - zihmekeqiwmweaiwsqitpeclevhasvolevh
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  schemas:
    - id: default
      url: file:///etc/kratos/identity-schemas/service/json/person.schema.json
  default_schema_id: "default"

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
